name: Nika Newsletter Issue

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch: 

jobs:
  prepare_newsletter_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.5'

      - name: Install dependencies
        run: |
          pip install python-dotenv google-genai pymongo markdown mailchimp-marketing certifi

      - name: Run script
        env:
          # This maps your GitHub Secrets to Environment Variables for Python
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_SERVER_PREFIX: ${{ secrets.MAILCHIMP_SERVER_PREFIX }}
          AUDIENCE_ID: ${{ secrets.MAILCHIMP_AUDIENCE_ID }}
        run: python workflow.py
